SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS fi_dir;
DROP TABLE IF EXISTS fi_file;
DROP TABLE IF EXISTS fi_ips;
DROP TABLE IF EXISTS fi_uniquedownloads;
DROP TABLE IF EXISTS fi_extensions;
SET FOREIGN_KEY_CHECKS=1;